/**
 * FORTBOT - Secure AI Agent over WhatsApp
 * Type definitions for capability-based security system
 * 
 * Inspired by:
 * - CaMeL (Google DeepMind) - Capability-based security for LLM agents
 * - FIDES - Information Flow Control with typed outputs
 * - PFI - Prompt Flow Integrity
 * - Simon Willison's Dual LLM pattern
 */

// ============================================================
// TRUST & TAINT SYSTEM
// ============================================================

/** Trust levels form a lattice: OWNER > SYSTEM > KNOWN_CONTACT > UNKNOWN > UNTRUSTED */
export enum TrustLevel {
  OWNER = 'owner',           // Messages from the owner (you)
  SYSTEM = 'system',         // System-generated data
  KNOWN_CONTACT = 'known',   // Messages from whitelisted contacts
  UNKNOWN = 'unknown',       // Messages from unknown contacts
  UNTRUSTED = 'untrusted',   // Data from web, files, external sources
}

/** Every value in the system carries a TaintLabel */
export interface TaintLabel {
  /** Where did this data originate? */
  origin: DataOrigin;
  /** Trust level assigned at ingestion */
  trust: TrustLevel;
  /** What created this value? */
  createdBy: string;
  /** Timestamp of creation */
  createdAt: number;
  /** Has this value been derived from untrusted data? (taint propagation) */
  tainted: boolean;
  /** Chain of transformations applied to this value */
  provenance: string[];
}

export interface DataOrigin {
  source: 'whatsapp' | 'web' | 'filesystem' | 'api' | 'user_input' | 'llm_output' | 'system';
  /** WhatsApp JID, URL, file path, etc. */
  identifier: string;
  /** Additional context */
  metadata?: Record<string, string>;
}

// ============================================================
// TYPED OUTPUT SYSTEM (FIDES-inspired)
// ============================================================

/**
 * Output schemas constrain what the Quarantined LLM can return.
 * Low-capacity types (boolean, enum) cannot carry prompt injection payloads.
 * High-capacity types (string) can carry payloads and are treated with more suspicion.
 */
export enum OutputCapacity {
  /** Boolean: 1 bit of info. Cannot carry injection payload. */
  BOOLEAN = 'boolean',
  /** Enum: log2(N) bits. Bounded info, very hard to inject. */
  ENUM = 'enum',
  /** Number: bounded precision. Low injection risk. */
  NUMBER = 'number',
  /** Structured: JSON with known schema. Medium risk, inspectable. */
  STRUCTURED = 'structured',
  /** String: unbounded info. HIGH injection risk. Requires extra policy checks. */
  STRING = 'string',
}

export interface OutputSchema {
  type: OutputCapacity;
  /** For ENUM type: the allowed values */
  enumValues?: string[];
  /** For STRUCTURED type: JSON schema */
  jsonSchema?: Record<string, unknown>;
  /** For STRING type: max length (limits exfiltration bandwidth) */
  maxLength?: number;
  /** Description of what this output represents */
  description: string;
}

// ============================================================
// PLAN SYSTEM
// ============================================================

/** A Plan is a sequence of steps generated by the Privileged LLM */
export interface Plan {
  id: string;
  /** Original user query (trusted) */
  userQuery: string;
  /** Ordered steps to execute */
  steps: PlanStep[];
  /** When was this plan created */
  createdAt: number;
  /** Has the policy engine approved this plan? */
  approved: boolean;
  /** Policy violations found (if any) */
  violations: PolicyViolation[];
}

export interface PlanStep {
  id: string;
  /** What action to perform */
  action: ActionType;
  /** Parameters for the action (may reference outputs of previous steps) */
  params: Record<string, StepParam>;
  /** Expected output schema (enforced on quarantined LLM) */
  outputSchema: OutputSchema;
  /** Does this step require processing untrusted data? */
  requiresQuarantine: boolean;
  /** Dependencies on previous steps */
  dependsOn: string[];
}

export type StepParam =
  | { kind: 'literal'; value: string | number | boolean }
  | { kind: 'reference'; stepId: string; field: string }
  | { kind: 'user_input'; field: string };

/** Available actions the system can perform */
export enum ActionType {
  // WhatsApp actions
  SEND_MESSAGE = 'send_message',
  READ_MESSAGES = 'read_messages',
  SEARCH_CONTACTS = 'search_contacts',
  SEARCH_MESSAGES = 'search_messages',

  // Data processing (runs in quarantine)
  EXTRACT_DATA = 'extract_data',
  SUMMARIZE = 'summarize',
  TRANSLATE = 'translate',
  CLASSIFY = 'classify',
  ANSWER_QUESTION = 'answer_question',

  // System actions
  READ_FILE = 'read_file',
  WRITE_FILE = 'write_file',
  SHELL_EXEC = 'shell_exec',
  WEB_FETCH = 'web_fetch',
  SCHEDULE_TASK = 'schedule_task',

  // Browser actions (Playwright)
  BROWSE = 'browse',
  SCREENSHOT = 'screenshot',

  // Meta actions
  ASK_USER_CONFIRMATION = 'ask_user_confirmation',
  LOG_EVENT = 'log_event',
}

// ============================================================
// POLICY SYSTEM
// ============================================================

export interface SecurityPolicy {
  /** Unique policy name */
  name: string;
  /** Human-readable description */
  description: string;
  /** Rules that make up this policy */
  rules: PolicyRule[];
}

export interface PolicyRule {
  /** Which action does this rule apply to? (* for all) */
  action: ActionType | '*';
  /** Conditions that must be met */
  conditions: PolicyCondition[];
  /** What to do: allow, deny, or ask user */
  effect: 'allow' | 'deny' | 'ask_user';
  /** Priority (higher = evaluated first) */
  priority: number;
}

export interface PolicyCondition {
  /** What to check */
  field: string;
  /** Operator */
  operator: 'equals' | 'not_equals' | 'in' | 'not_in' | 'trust_gte' | 'trust_lte' | 'is_tainted' | 'capacity_lte';
  /** Value to compare against */
  value: unknown;
}

export interface PolicyViolation {
  stepId: string;
  rule: PolicyRule;
  reason: string;
  severity: 'critical' | 'warning' | 'info';
}

// ============================================================
// CAPABILITY TOKENS (CaMeL-inspired)
// ============================================================

/**
 * A Capability is an unforgeable token that grants specific permissions on a value.
 * Values without capabilities cannot be used in security-sensitive operations.
 */
export interface Capability {
  /** Unique ID for this capability */
  id: string;
  /** What value does this capability protect? */
  valueId: string;
  /** What operations are permitted? */
  permissions: Permission[];
  /** Who granted this capability? */
  grantedBy: 'owner' | 'policy_engine' | 'system';
  /** Expiration */
  expiresAt?: number;
  /** Is this capability revoked? */
  revoked: boolean;
}

export enum Permission {
  READ = 'read',
  SEND_TO_OWNER = 'send_to_owner',
  SEND_TO_KNOWN = 'send_to_known',
  SEND_TO_ANYONE = 'send_to_anyone',
  WRITE_FILE = 'write_file',
  EXECUTE = 'execute',
  PASS_TO_API = 'pass_to_api',
}

// ============================================================
// TAINTED VALUE WRAPPER
// ============================================================

/**
 * Every piece of data flowing through the system is wrapped in a TaintedValue.
 * This ensures taint labels and capabilities travel with the data.
 */
export interface TaintedValue<T = unknown> {
  /** The actual value */
  value: T;
  /** Taint label tracking origin and trust */
  label: TaintLabel;
  /** Capabilities granting permissions on this value */
  capabilities: Capability[];
  /** Output capacity type (from FIDES) */
  capacity: OutputCapacity;
}

// ============================================================
// EXECUTION RESULTS
// ============================================================

export interface ExecutionResult {
  planId: string;
  stepId: string;
  success: boolean;
  output?: TaintedValue;
  error?: string;
  /** Time taken in ms */
  duration: number;
  /** Was user confirmation required? */
  userConfirmationRequired: boolean;
  /** Full audit log entry */
  auditEntry: AuditEntry;
}

export interface AuditEntry {
  timestamp: number;
  planId: string;
  stepId: string;
  action: ActionType;
  /** Input taint labels */
  inputLabels: TaintLabel[];
  /** Output taint label */
  outputLabel?: TaintLabel;
  /** Policy decision */
  policyDecision: 'allow' | 'deny' | 'ask_user';
  /** Was it executed? */
  executed: boolean;
  /** Any warnings */
  warnings: string[];
}

// ============================================================
// GATEWAY MESSAGE TYPES
// ============================================================

export interface IncomingMessage {
  /** WhatsApp JID of sender */
  from: string;
  /** Display name */
  fromName: string;
  /** Is this a group message? */
  isGroup: boolean;
  /** Group JID if applicable */
  groupId?: string;
  /** Message content */
  content: string;
  /** Message type */
  type: 'text' | 'image' | 'video' | 'audio' | 'document';
  /** Media URL if applicable */
  mediaUrl?: string;
  /** Raw media buffer (for audio/image download) */
  mediaBuffer?: Buffer;
  /** Timestamp */
  timestamp: number;
  /** Assigned trust level */
  trust: TrustLevel;
}

export interface OutgoingMessage {
  /** WhatsApp JID of recipient */
  to: string;
  /** Message content */
  content: string;
  /** Capability token authorizing this send */
  capability: Capability;
}

// ============================================================
// SYSTEM CONFIGURATION
// ============================================================

export interface FortBotConfig {
  /** Your WhatsApp number (the OWNER) — you message FROM this number */
  ownerNumber: string;
  /** Known/trusted contacts */
  knownContacts: string[];
  /** Model for the Privileged LLM (planner). Uses your Max subscription. */
  plannerModel: 'sonnet' | 'opus' | 'haiku';
  /** Model for the Quarantined LLM. Uses your Max subscription. */
  quarantineModel: 'sonnet' | 'opus' | 'haiku';
  /** Use local LLM for quarantine instead of Claude? (max privacy) */
  useLocalQuarantine: boolean;
  /** Local LLM endpoint (ollama, llama.cpp, etc.) */
  quarantineLlmEndpoint: string;
  /** Use Docker for quarantine sandbox? (false = Firecracker when available) */
  useDockerSandbox: boolean;
  /** Security policies */
  policies: SecurityPolicy[];
  /** Actions that always require user confirmation */
  alwaysConfirmActions: ActionType[];
  /** Maximum plan steps */
  maxPlanSteps: number;
  /** Audit log path */
  auditLogPath: string;
  /** Kill switch phrase (send via WhatsApp to stop everything) */
  killSwitchPhrase: string;
  /** SQLite database path */
  dbPath: string;
  /** Human emulation config (anti-detection) */
  humanConfig?: Partial<{
    wakeHour: number;
    sleepHour: number;
    typingSpeedMin: number;
    typingSpeedMax: number;
    readDelayMin: number;
    readDelayMax: number;
    sendJitterMin: number;
    sendJitterMax: number;
    offlineFlickerChance: number;
    offlineFlickerMin: number;
    offlineFlickerMax: number;
    maxMessagesPerMinute: number;
    maxMessagesPerHour: number;
  }>;
}
